//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCare.CarCareDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaseRecord
    {
        public long LeaseId { get; set; }
        public long VehicleId { get; set; }
        public Nullable<System.DateTime> LeaseStartDate { get; set; }
        public int LeaseTerm { get; set; }
        public decimal MonthlyPayment { get; set; }
        public string Company { get; set; }
        public Nullable<decimal> MoneyFactor { get; set; }
        public Nullable<int> MilesDrivenPerYear { get; set; }
        public Nullable<decimal> AcquistionFee { get; set; }
        public Nullable<decimal> SecurityDeposit { get; set; }
        public string LeaseNotes { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
