//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCare.CarCareDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRecord
    {
        public long ServiceId { get; set; }
        public long VehicleId { get; set; }
        public long ServiceTypeId { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public Nullable<long> ServiceStationId { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<decimal> ServiceCost { get; set; }
    
        public virtual ServiceType ServiceType { get; set; }
        public virtual ServiceStation ServiceStation { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
