//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCare.CarCareDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuneUp
    {
        public long TuneUpId { get; set; }
        public long VehicleId { get; set; }
        public long OwnerId { get; set; }
        public string ServiceProvider { get; set; }
        public System.DateTime TuneupDate { get; set; }
        public System.DateTime NextTuneup { get; set; }
        public decimal Cost { get; set; }
    }
}
