//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCare.CarCareDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleSummary
    {
        public long UserId { get; set; }
        public long VehicleId { get; set; }
        public long ServiceId { get; set; }
        public long RepairId { get; set; }
    }
}
